# Generated by Django 3.0.5 on 2020-06-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ClasseEtudiant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='password',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='num',
            field=models.CharField(default='', max_length=7, unique=True),
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomPromo', models.CharField(max_length=50)),
                ('listeEtu', models.ManyToManyField(to='ClasseEtudiant.Etudiant')),
            ],
        ),
    ]
